const fs = require('fs');
const path = require('path');

const unitsPath = path.join(__dirname, '../data/unidades.json');
const rawData = fs.readFileSync(unitsPath, 'utf8');
const unitsData = JSON.parse(rawData);

const barbarianUnits = [
    {
        "nombre-unidad": "agitador-hachas-barbaro",
        "generales": 0,
        "puntos-golpe": 1120,
        "armadura": 20,
        "daño": 360,
        "precision": 100,
        "daño-mejora1": 360,
        "daño-mejora2": 360,
        "daño-mejora3": 360,
        "armadura-mejora1": 20,
        "armadura-mejora2": 20,
        "armadura-mejora3": 20,
        "tamaño": 1,
        "municion": null,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "primera-linea"
    },
    {
        "nombre-unidad": "aporreador-barbaro",
        "generales": 0,
        "puntos-golpe": 240,
        "armadura": 20,
        "daño": 100,
        "precision": 100,
        "daño-mejora1": 100,
        "daño-mejora2": 100,
        "daño-mejora3": 100,
        "armadura-mejora1": 20,
        "armadura-mejora2": 20,
        "armadura-mejora3": 20,
        "tamaño": 1,
        "municion": null,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "flancos"
    },
    {
        "nombre-unidad": "unidad-guerra-barbara",
        "generales": 0,
        "puntos-golpe": 3680,
        "armadura": 60,
        "daño": 840,
        "precision": 100,
        "daño-mejora1": 840,
        "daño-mejora2": 840,
        "daño-mejora3": 840,
        "armadura-mejora1": 60,
        "armadura-mejora2": 60,
        "armadura-mejora3": 60,
        "tamaño": 3,
        "municion": null,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "primera-linea"
    },
    {
        "nombre-unidad": "clava-cuchillos-barbaro",
        "generales": 0,
        "puntos-golpe": 360,
        "armadura": 0,
        "daño": 200,
        "precision": 100,
        "daño-mejora1": 200,
        "daño-mejora2": 200,
        "daño-mejora3": 200,
        "armadura-mejora1": 0,
        "armadura-mejora2": 0,
        "armadura-mejora3": 0,
        "tamaño": 1,
        "municion": null,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "flancos"
    },
    {
        "nombre-unidad": "lanzahachas-barbaro",
        "generales": 0,
        "puntos-golpe": 320,
        "armadura": 0,
        "daño": 200,
        "precision": 100,
        "daño-mejora1": 200,
        "daño-mejora2": 200,
        "daño-mejora3": 200,
        "armadura-mejora1": 0,
        "armadura-mejora2": 0,
        "armadura-mejora3": 0,
        "tamaño": 1,
        "municion": 7,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "luchadores-distancia"
    },
    {
        "nombre-unidad": "ariete-barbaro",
        "generales": 0,
        "puntos-golpe": 1400,
        "armadura": 20,
        "daño": 2100,
        "precision": 100,
        "daño-mejora1": 2100,
        "daño-mejora2": 2100,
        "daño-mejora3": 2100,
        "armadura-mejora1": 20,
        "armadura-mejora2": 20,
        "armadura-mejora3": 20,
        "tamaño": 5,
        "municion": 7,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "artilleria"
    },
    {
        "nombre-unidad": "catapulta-barbara",
        "generales": 0,
        "puntos-golpe": 640,
        "armadura": 0,
        "daño": 5400,
        "precision": 100,
        "daño-mejora1": 5400,
        "daño-mejora2": 5400,
        "daño-mejora3": 5400,
        "armadura-mejora1": 0,
        "armadura-mejora2": 0,
        "armadura-mejora3": 0,
        "tamaño": 5,
        "municion": 5,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "artilleria"
    },
    {
        "nombre-unidad": "dirigible-barbaro",
        "generales": 0,
        "puntos-golpe": 800,
        "armadura": 0,
        "daño": 960,
        "precision": 100,
        "daño-mejora1": 960,
        "daño-mejora2": 960,
        "daño-mejora3": 960,
        "armadura-mejora1": 0,
        "armadura-mejora2": 0,
        "armadura-mejora3": 0,
        "tamaño": 2,
        "municion": 2,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "bombarderos"
    },
    {
        "nombre-unidad": "caza-barbaro",
        "generales": 0,
        "puntos-golpe": 580,
        "armadura": 0,
        "daño": 340,
        "precision": 100,
        "daño-mejora1": 340,
        "daño-mejora2": 340,
        "daño-mejora3": 340,
        "armadura-mejora1": 0,
        "armadura-mejora2": 0,
        "armadura-mejora3": 0,
        "tamaño": 1,
        "municion": 4,
        "tipo-batalla": "terrestre",
        "tipo-unidad": "anti-aerea"
    },
    {
        "nombre-unidad": "rompelanchas",
        "generales": 0,
        "puntos-golpe": 3080,
        "armadura": 240,
        "daño": 1500,
        "precision": 100,
        "daño-mejora1": 1500,
        "daño-mejora2": 1500,
        "daño-mejora3": 1500,
        "armadura-mejora1": 240,
        "armadura-mejora2": 240,
        "armadura-mejora3": 240,
        "tamaño": 3,
        "municion": null,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "flancos"
    },
    {
        "nombre-unidad": "rajavelas",
        "generales": 0,
        "puntos-golpe": 3080,
        "armadura": 280,
        "daño": 800,
        "precision": 100,
        "daño-mejora1": 800,
        "daño-mejora2": 800,
        "daño-mejora3": 800,
        "armadura-mejora1": 280,
        "armadura-mejora2": 280,
        "armadura-mejora3": 280,
        "tamaño": 2,
        "municion": 7,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "luchadores-distancia"
    },
    {
        "nombre-unidad": "pirobarco",
        "generales": 0,
        "puntos-golpe": 4380,
        "armadura": 220,
        "daño": 1640,
        "precision": 100,
        "daño-mejora1": 1640,
        "daño-mejora2": 1640,
        "daño-mejora3": 1640,
        "armadura-mejora1": 220,
        "armadura-mejora2": 220,
        "armadura-mejora3": 220,
        "tamaño": 2,
        "municion": 7,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "primera-linea"
    },
    {
        "nombre-unidad": "tiraguijarros",
        "generales": 0,
        "puntos-golpe": 2960,
        "armadura": 200,
        "daño": 900,
        "precision": 100,
        "daño-mejora1": 900,
        "daño-mejora2": 900,
        "daño-mejora3": 900,
        "armadura-mejora1": 200,
        "armadura-mejora2": 200,
        "armadura-mejora3": 200,
        "tamaño": 3,
        "municion": 8,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "luchadores-distancia"
    },
    {
        "nombre-unidad": "cuña",
        "generales": 0,
        "puntos-golpe": 11520,
        "armadura": 400,
        "daño": 3320,
        "precision": 100,
        "daño-mejora1": 3320,
        "daño-mejora2": 3320,
        "daño-mejora3": 3320,
        "armadura-mejora1": 400,
        "armadura-mejora2": 400,
        "armadura-mejora3": 400,
        "tamaño": 4,
        "municion": null,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "primera-linea"
    },
    {
        "nombre-unidad": "catapulta-polvora",
        "generales": 0,
        "puntos-golpe": 3080,
        "armadura": 120,
        "daño": 1500,
        "precision": 100,
        "daño-mejora1": 1500,
        "daño-mejora2": 1500,
        "daño-mejora3": 1500,
        "armadura-mejora1": 120,
        "armadura-mejora2": 120,
        "armadura-mejora3": 120,
        "tamaño": 4,
        "municion": 11,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "luchadores-distancia"
    },
    {
        "nombre-unidad": "terror-profundidades-marinas",
        "generales": 0,
        "puntos-golpe": 1600,
        "armadura": 120,
        "daño": 2800,
        "precision": 100,
        "daño-mejora1": 2800,
        "daño-mejora2": 2800,
        "daño-mejora3": 2800,
        "armadura-mejora1": 120,
        "armadura-mejora2": 120,
        "armadura-mejora3": 120,
        "tamaño": 3,
        "municion": 6,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "artilleria"
    },
    {
        "nombre-unidad": "fuego-dragon",
        "generales": 0,
        "puntos-golpe": 2200,
        "armadura": 180,
        "daño": 7000,
        "precision": 100,
        "daño-mejora1": 7000,
        "daño-mejora2": 7000,
        "daño-mejora3": 7000,
        "armadura-mejora1": 180,
        "armadura-mejora2": 180,
        "armadura-mejora3": 180,
        "tamaño": 4,
        "municion": 3,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "artilleria"
    },
    {
        "nombre-unidad": "encendedor-zepelin",
        "generales": 0,
        "puntos-golpe": 400,
        "armadura": 60,
        "daño": 340,
        "precision": 100,
        "daño-mejora1": 340,
        "daño-mejora2": 340,
        "daño-mejora3": 340,
        "armadura-mejora1": 60,
        "armadura-mejora2": 60,
        "armadura-mejora3": 60,
        "tamaño": 1,
        "municion": 5,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "anti-aerea"
    },
    {
        "nombre-unidad": "Nido-barbaros",
        "generales": 0,
        "puntos-golpe": 2800,
        "armadura": 100,
        "daño": 2000,
        "precision": 100,
        "daño-mejora1": 2000,
        "daño-mejora2": 2000,
        "daño-mejora3": 2000,
        "armadura-mejora1": 100,
        "armadura-mejora2": 100,
        "armadura-mejora3": 100,
        "tamaño": 5,
        "municion": 5,
        "tipo-batalla": "maritimo",
        "tipo-unidad": "bombarderos"
    }
];

// Check if units already exist to avoid duplicates
const existingNames = new Set(unitsData.unit.map(u => u['nombre-unidad']));
let addedCount = 0;

barbarianUnits.forEach(unit => {
    if (!existingNames.has(unit['nombre-unidad'])) {
        unitsData.unit.push(unit);
        addedCount++;
    } else {
        console.log(`Unit ${unit['nombre-unidad']} already exists, skipping.`);
    }
});

fs.writeFileSync(unitsPath, JSON.stringify(unitsData, null, 2), 'utf8');
console.log(`Successfully added ${addedCount} barbarian units.`);
